# Generated by Django 4.1.5 on 2023-01-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_departments_roles_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
