# Generated by Django 4.1.5 on 2023-01-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_departments_department_rename_roles_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='zipcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
