# Generated by Django 4.1.5 on 2023-01-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_department_id_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='zipcode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
