# Generated by Django 4.1.5 on 2023-01-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_employee_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='zipcode',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
